import type {Metadata} from "next";
import "./globals.css";
import Navigation from "@/components/navigation/navigation";

export const metadata: Metadata = {
  title: "Pwa Spike",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className="flex h-screen">
    <Navigation/>
    <main className="bg-gray-300 p-10 md:p-24 flex-grow">
      {children}
    </main>
    </body>
    </html>
  );
}
